Repository adobe-experience-league/exlm, pull requests merged in 2024-03, with the labels that each got.

#577 EXLM-1175 Highlights CSS
  styles/styles.css
  styles/styles.scss
Labels: Do-not-merge

#609 chore: improve script loading for UE
  scripts/editor-support-rte.js
  scripts/editor-support.js
  scripts/lib-franklin.js
Labels: Do-not-merge

#653 EXLM-1158 Search - automatic pre-filters for solution
  scripts/search/search.js
Labels: Sprint 9

#654 EXLM 1182 Recommended Courses Duration Calculation
  scripts/browse-card/browse-card.js
  scripts/browse-card/browse-cards-delegate.js
Labels: Do-not-merge, Sprint 9

#655 Marquee Video load
  blocks/marquee/marquee.css
  blocks/marquee/marquee.js
  component-models.json
Labels: Do-not-merge, Sprint 9

#659 EXLM1182 Recommended Courses Support for Zh and PT
  scripts/browse-card/browse-cards-delegate.js
Labels: Sprint 9

#661 EXLM-1222 Open on demand content in same tab
  scripts/browse-card/browse-card.js
Labels: Sprint 9

#668 EXLM-1166 Date filter for tabbed cards
  component-models.json
Labels: Sprint 9

#683 Hotfix - Html elements in Table fix
  blocks/table/table.js
Labels: MVP Release - hotfix

#669 Update modal style for Video in Marquee
  blocks/marquee/marquee.css
  blocks/marquee/marquee.js
Labels: Sprint 9

#691 EXLM-1246 Feedback bar
  scripts/feedback/feedback.js
Labels: Sprint 9

#698 EXLM-1166 Filter by Date for tabbed cards
  component-models.json
Labels: Sprint 9

#690 EXLM 1161 Featured Card Filters
  blocks/featured-cards/featured-cards.js
  scripts/dropdown/dropdown.js
Labels: Sprint 9

#665 EXLM-1214: Ability to control navigation order
  blocks/browse-rail/browse-rail.js
Labels: Sprint 9
