Repository adobe-experience-league/exlm, pull requests merged in 2024-04, with the labels that each got.

#737 EXLM-1210 Article Marquee block
  component-definition.json
  component-filters.json
  component-models.json
Labels: Sprint 11

#745 EXLM 1297- Remove spacing around teaser
  blocks/detailed-teaser/detailed-teaser.css
  blocks/marquee/marquee.css
  blocks/sign-up/sign-up.css
  styles/styles.css
  styles/styles.scss
Labels: Sprint 11

#743 EXLM 1299 Header Featured Products
  blocks/header/header.js
Labels: Sprint 11

#761 EXLM 1297 Spacing Issue
  blocks/recommended-courses/recommended-courses.js
Labels: Sprint 11

#759 EXLM 1304 Block Quote
  blocks/block-quote/block-quote.css
  blocks/block-quote/block-quote.js
  component-definition.json
  component-filters.json
  component-models.json
  styles/styles.css
Labels: Sprint 11

#766 EXLM 1304 Block Quote Theme Update
  blocks/block-quote/block-quote.js
Labels: Sprint 11

#768 EXLM 1210 - Add article pages index
  helix-query.yaml
Labels: Sprint 11

#775 EXLM 1303 Callout Block UE Changes
  component-definition.json
  component-filters.json
  component-models.json
Labels: Sprint 11

#760 EXLM 1208 - Thought leadership landing page theme
  blocks/articles-rail/articles-rail-utils.js
  blocks/articles-rail/articles-rail.css
  blocks/articles-rail/articles-rail.js
  scripts/scripts.js
  styles/styles.css
  styles/styles.scss
Labels: Sprint 11

#778 EXLM-1272: deselecting the browse topic, previous value is still in datalayer
  scripts/analytics/lib-analytics.js
Labels: Draft

#797 EXLM 1283 Author Bio Pages Block
  blocks/author-bio/author-bio.css
  blocks/author-bio/author-bio.js
  component-definition.json
  component-filters.json
  component-models.json
Labels: Sprint 12
